<#
.SYNOPSIS
  OhShit 一键安装脚本（Windows PowerShell / PowerShell 7+）
  直接右键 → 使用 PowerShell 运行，或在 pwsh 内执行：
  Set-ExecutionPolicy RemoteSigned -Scope CurrentUser ; .\danger_guard\scripts\install.ps1
#>
$ErrorActionPreference = "Stop"

function Write-Info($m)  { Write-Host "[ohshit install] " -ForegroundColor Cyan  -NoNewline; Write-Host $m }
function Write-Warn($m)  { Write-Host "[ohshit install] " -ForegroundColor Yellow -NoNewline; Write-Warning $m }
function Write-Ok($m)    { Write-Host "[ohshit install] " -ForegroundColor Green  -NoNewline; Write-Host $m }
function Write-Err($m)   { Write-Host "[ohshit install] " -ForegroundColor Red    -NoNewline; Write-Error $m }

# ---------- 基础检查 ----------
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
  Write-Err "系统未找到 python。请先安装 Python 3.7+ (python.org/downloads/windows)"; exit 1
}
$pyVer = python -c "import sys; sys.stdout.write(str(sys.version_info[:2]))"
Write-Info "Python 版本: $pyVer"

$InstallDir   = Join-Path $env:USERPROFILE ".ohshit"
$BinDir       = Join-Path $env:USERPROFILE ".ohshit\bin"
$PackageDir   = Join-Path $InstallDir "lib"
$BackupDir    = Join-Path $InstallDir "backups\$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$Wrapper      = Join-Path $BinDir "dang.cmd"
$OhShitWrapper= Join-Path $BinDir "ohshit.cmd"

New-Item -ItemType Directory -Force -Path $InstallDir, $BinDir, $PackageDir, $BackupDir | Out-Null
Write-Info "安装目录: $InstallDir"

# ---------- Step A: pip install ----------
$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $ScriptDir))  # danger_guard\scripts\ -> project root
if ((Test-Path (Join-Path $ProjectRoot "pyproject.toml")) -and (Get-Content (Join-Path $ProjectRoot "pyproject.toml") | Select-String "danger[_-]guard" -Quiet)) {
  Write-Info "发现项目根 $ProjectRoot，执行 pip install -e ..."
  try {
    python -m pip install --quiet -e $ProjectRoot
    Write-Ok "pip install 成功"
  } catch {
    Write-Warn "pip editable 失败，退回到复制包。"
    Copy-Item -Recurse -Force (Join-Path $ProjectRoot "danger_guard") $PackageDir
  }
} else {
  Write-Warn "未发现本地项目根目录。请先 git clone 再执行本脚本。"
}

python -c "from danger_guard.core.engine import run_pipeline"
if ($LASTEXITCODE -ne 0) {
  Write-Warn "danger_guard 导入失败，改用本地目录："
  if (-not (Test-Path (Join-Path $PackageDir "danger_guard"))) { Write-Err "未找到 danger_guard 包"; exit 1 }
  Copy-Item -Recurse -Force (Join-Path $PackageDir "danger_guard") (Join-Path $InstallDir "danger_guard")
}

# ---------- Step B: 写 dang.cmd / ohshit.cmd ----------
function Write-Wrapper($Target) {
  if (Test-Path $Target) {
    Move-Item -Force $Target (Join-Path $BackupDir ("$(Split-Path -Leaf $Target)-$(Get-Random)"))
    Write-Info "备份旧文件到 $BackupDir"
  }
  @"
@echo off
REM OhShit wrapper (generated by install.ps1)
REM 若 ~/.ohshit 下有 danger_guard 包，优先加入 PYTHONPATH
set OHSHIT_DIR=%USERPROFILE%\.ohshit
set PYTHONPATH=%OHSHIT_DIR%\lib;%OHSHIT_DIR%;%PYTHONPATH%
python -m danger_guard %*
exit /b %ERRORLEVEL%
"@ | Set-Content -Encoding ASCII $Target
  Write-Ok "写入 $Target"
}

Write-Wrapper $Wrapper
Write-Wrapper $OhShitWrapper

# ---------- Step C: 把 $BinDir 加入用户 PATH ----------
$UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($UserPath -notlike "*$BinDir*") {
  [Environment]::SetEnvironmentVariable("PATH", "$UserPath;$BinDir", "User")
  Write-Ok "已将 $BinDir 加入用户 PATH（当前终端需重新打开生效）"
  $env:PATH = "$env:PATH;$BinDir"
} else {
  Write-Info "PATH 已包含 $BinDir，跳过"
}

# ---------- Step D: 写 profile 里的 Remove-Item / dd 包装函数 ----------
$ProfileContent = @"

# >>> OhShit 删库跑路预防针 >>>
# 交互 shell 下重写 Remove-Item 和 dd 的友好包装
if (`$Host.Name -match 'Console|ISE|Visual Studio Code' -or `$PSVersionTable.PSVersion.Major -ge 7) {
  function global:Remove-Item {
    [CmdletBinding(SupportsShouldProcess = `$true)]
    param(
      [Parameter(Position = 0, ValueFromRemainingArguments = `$true, ValueFromPipeline = `$true)]
      [string[]]`$Path,
      [switch]`$Recurse, [switch]`$Force, [switch]`$Verbose, [switch]`$WhatIf
    )
    process {
      if (`$WhatIf) { return Microsoft.PowerShell.Management\Remove-Item @PSBoundParameters }
      if (-not `$Path -or `$Path.Count -eq 0) { return Microsoft.PowerShell.Management\Remove-Item @PSBoundParameters }
      # 路径敏感判断：只在 -Recurse -Force 且有 * 或根路径时才拦截
      `$Intercept = (`$Recurse -and (`$Force -or (`$Path -match '\\\*$|/\*$|^[A-Z]:\\$|^/home|^/root|^/etc|^/var|^/usr')))
      if (`$Intercept) {
        `$Flags = @()
        if (`$Recurse) { `$Flags += '-Recurse' }
        if (`$Force)   { `$Flags += '-Force'   }
        if (`$Verbose) { `$Flags += '-Verbose' }
        dang -- rm @Flags @Path
      } else {
        Microsoft.PowerShell.Management\Remove-Item @PSBoundParameters
      }
    }
  }
}
# <<< OhShit 删库跑路预防针 <<<
"@

$ProfileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path $ProfileDir)) { New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null }
if (Test-Path $PROFILE) {
  Copy-Item $PROFILE (Join-Path $BackupDir "profile-backup.ps1")
}
if (-not (Get-Content $PROFILE -ErrorAction SilentlyContinue | Select-String "OhShit 删库跑路预防针" -Quiet)) {
  Add-Content -Encoding UTF8 -Path $PROFILE -Value $ProfileContent
  Write-Ok "已注入 PowerShell Profile: $PROFILE"
} else {
  Write-Info "Profile 已注入，跳过"
}

# ---------- 结束 ----------
Write-Ok "✅ 安装完成！执行："
Write-Host "   1) 重新打开一个 PowerShell 窗口（加载 Profile 与 PATH）"
Write-Host "   2) dang --list-hooks"
Write-Host "   3) dang --dry-run -- rm -rf C:\temp\*"
